/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.wquintal.yvan.lab1;

import ca.wquintal.yvan.lab1.Auth;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author wq
 */
public class AuthFrame extends java.awt.Frame {

	public String getUsername() {
		return username;
	}

	public String getPassword() {
		return password;
	}

	public Boolean getIsauth() {
		return isauth;
	}

    private String username, password;
    private Boolean isauth;
    /**
     * Creates new form AuthFrame
     */
    public AuthFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panel1 = new java.awt.Panel();
                label1 = new java.awt.Label();
                btnLogin = new java.awt.Button();
                txtPassword = new java.awt.TextField();
                txtUsername = new java.awt.TextField();
                label2 = new java.awt.Label();

                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosing(java.awt.event.WindowEvent evt) {
                                exitForm(evt);
                        }
                });

                label1.setText("label1");
                add(label1, java.awt.BorderLayout.WEST);

                btnLogin.setActionCommand("btnLogin");
                btnLogin.setLabel("kkkl");
                btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseReleased(java.awt.event.MouseEvent evt) {
                                btnLoginMouseReleased(evt);
                        }
                });
                add(btnLogin, java.awt.BorderLayout.SOUTH);
                btnLogin.getAccessibleContext().setAccessibleName("btnLogin");

                txtPassword.setText("linux");
                add(txtPassword, java.awt.BorderLayout.CENTER);

                txtUsername.setText("wquintal");
                add(txtUsername, java.awt.BorderLayout.NORTH);

                label2.setText("label2");
                add(label2, java.awt.BorderLayout.EAST);

                pack();
        }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseReleased
    	// Quand on veut ce login, recupere le username et mot de passe
        this.username = txtUsername.getText();
    	this.password = txtPassword.getText();

        if(!Auth.AuthUser(this.username,this.password)) {
            return;
        }
        Auth.OnLoginSuccessful(this.username);
        this.isauth = true;
        this.dispose();
        System.out.print("Auth frame is close");
        if(this.getIsauth()) {
            GestionFichierJDialog dialog = new GestionFichierJDialog(new javax.swing.JFrame(), true,"wquintal");
            dialog.setVisible(true);
	    
	    dialog.addWindowListener(new WindowAdapter() {
		@Override 
		public void windowClosed(WindowEvent e) {
			System.exit(0);
		}
		
	});
	
        }
    }//GEN-LAST:event_btnLoginMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthFrame().setVisible(true);
            }
        });
    }


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private java.awt.Button btnLogin;
        private java.awt.Label label1;
        private java.awt.Label label2;
        private java.awt.Panel panel1;
        private java.awt.TextField txtPassword;
        private java.awt.TextField txtUsername;
        // End of variables declaration//GEN-END:variables
}
